### ISSUE TITLE
Libraries and Board Settings 

### ISSUE THREAD

**Issue by wonderingwombat** [Xinyuan-LilyGO/LilyGo-HeartRate-Kit#1]
Hi,

I'm using the Arduino IDE. I have followed the instructions given in the readme but I was wondering if you can confirm if any additional libraries need to be installed and what Board settings need to be selected?

**Comment by wonderingwombat** [comment]
It might be easier to use PlatformIO rather than the ArduinoIDE. On a mac I was able to set this up using using Homebrew and with SubmlimeText installed using the following commands. 
- Install PlatformIO `brew install platformio`
- Create a blank project `platformio project init --ide sublimetext --board esp32dev`
- Copy the files from the repository into the blank project. 
- Run `platformio run` to build the project.

**Comment by lewisxhe** [comment]
Has the problem been solved?  Please close if resolved.

**Comment by wonderingwombat** [comment]
I'd still like to find out what is needed to run the code on the Arduino IDE, if possible? Or is PlatformIO the recommended environment?

**Comment by lewisxhe** [comment]
The corresponding operations in ArduinoIDE and PlatformIO have been explained in the README. You can choose which IDE you want to use.
@wonderingwombat

**Comment by wonderingwombat** [comment]
Okay thanks.
